name: CI Pipeline

on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build Lambda
        run: ./gradlew jar -i

      - name: Code Analysis
        run: ./gradlew lint -i

      - name: Unit Tests
        run: ./gradlew test -i

      - name: Integration Tests
        run: ./gradlew integrationTest -i
